node {

  stage('Test') {
    dir ('server/gokbg3') {
      sh './gradlew --no-daemon --console plain clean test'
    }
  }

  stage('Build') {
    dir ('server/gokbg3') {
      sh './gradlew --no-daemon --console plain clean war'
    }
    exports = findFiles glob: 'build/libs/*.jar'
  }
}
