node {


  stage('Test') {
    sh './gradlew --no-daemon --console plain clean test-app'
  }

  stage('Build') {
    sh './gradlew --no-daemon --console plain clean war'
    exports = findFiles glob: 'build/libs/*.jar'
  }

}
