node {

  stage('Test') {
    dir ('server/gokbg3') {
      sh 'pwd; ls -la; ./gradlew --no-daemon --console plain clean test-app'
    }
  }

  stage('Build') {
    dir ('server/gokbg3') {
      sh './gradlew --no-daemon --console plain clean war'
    }
    exports = findFiles glob: 'build/libs/*.jar'
  }
}
