
SET foreign_key_checks = 0;
truncate table additional_property_definition;
truncate table audit_log;
truncate table batch_control;
truncate table combo;
truncate table combo_criteria;
truncate table document;
truncate table identifier;
truncate table identifier_namespace;
truncate table identifier_occurrence;
truncate table kb_component_refdata_value;
truncate table kbcomponent;
truncate table kbcomponent_additional_property;
truncate table note;
truncate table org_role;
truncate table refdata_category;
truncate table refdata_value;
truncate table refine_operation;
truncate table refine_project;
truncate table registration_code;
truncate table role;
truncate table rule;
truncate table user;
truncate table user_role;
truncate table utils;

drop table additional_property_definition;
drop table audit_log;
drop table batch_control;
drop table combo;
drop table combo_criteria;
drop table document;
drop table identifier;
drop table identifier_namespace;
drop table identifier_occurrence;
drop table kb_component_refdata_value;
drop table kbcomponent;
drop table kbcomponent_additional_property;
drop table note;
drop table org_role;
drop table refdata_category;
drop table refdata_value;
drop table refine_operation;
drop table refine_project;
drop table registration_code;
drop table role;
drop table rule;
drop table user;
drop table user_role;
drop table utils;
drop table kb_component_tags_value;
drop table org_refdata_value;
drop table platform_refdata_value;

SET foreign_key_checks = 1;
